repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.6
  hooks:
    - id: autopep8

- repo: local
  hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest
      always_run: true
      pass_filenames: false
